#PRACTICE PROBLEM 1

SELECT CR.CASE_NUMBER, CR.PRIMARY_TYPE, CE.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME CR
INNER JOIN CHICAGO_CENSUS CE
ON CR.COMMUNITY_AREA_NUMBER = CE.COMMUNITY_AREA_NUMBER
WHERE CR.COMMUNITY_AREA_NUMBER = 18;

#PRACTICE PROBLEM 2

SELECT CR.CASE_NUMBER, CR.PRIMARY_TYPE, CE.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME CR
LEFT OUTER JOIN CHICAGO_CENSUS CE
ON CR.COMMUNITY_AREA_NUMBER = CE.COMMUNITY_AREA_NUMBER 
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%';

#PRACTICE PROBLEM 3

SELECT CR.CASE_NUMBER, CE.COMMUNITY_AREA_NUMBER
FROM CHICAGO_CRIME CR
FULL OUTER JOIN CHICAGO_CENSUS CE
ON CR.COMMUNITY_AREA_NUMBER = CE.COMMUNITY_AREA_NUMBER
WHERE CE.COMMUNITY_AREA_NAME IN( 'Oakland', 'Armour Square', 'Edgewaterm', 'CHICAGO'); #CREO QUE QUEDÓ MAL